eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
server:
  port: ${PORT:0}
spring:
  application:
    name: auth-ws
  datasource:
    password: pass@word1
    url: jdbc:mysql://localhost:3306/stock?useSSL=false
    username: root
  devtools:
    restart:
      enabled: true
  boot:
    admin:
      client:
        url: http://localhost:9999